In [1]:
from pyodk.client import Client
import pandas as pd

In [3]:
with Client(config_path='.pyodk_config.toml', cache_path='cache.toml') as client:
    submissions = client.submissions.get_table(form_id='lp_2025_2026')
    dff = pd.json_normalize(data=submissions['value'], sep='/')

In [ ]:
dff.to_csv('lp202526.csv')
dff

In [5]:
def clean(dff):
    # Loaded variable 'dff' from kernel state

    # Drop column: 'phone_number'
    dff = dff.drop(columns=['phone_number'])

    # Drop column: '__id'
    dff = dff.drop(columns=['__id'])

    # Drop column: 'gis_location/xy/type'
    dff = dff.drop(columns=['gis_location/xy/type'])

    # Drop column: 'gis_location/xy/properties/accuracy'
    dff = dff.drop(columns=['gis_location/xy/properties/accuracy'])

    # Drop column: '__system/status'
    dff = dff.drop(columns=['__system/status'])

    # Drop column: '__system/attachmentsPresent'
    dff = dff.drop(columns=['__system/attachmentsPresent'])

    # Drop column: '__system/attachmentsExpected'
    dff = dff.drop(columns=['__system/attachmentsExpected'])

    # Drop column: '__system/reviewState'
    dff = dff.drop(columns=['__system/reviewState'])

    # Drop column: '__system/deviceId'
    dff = dff.drop(columns=['__system/deviceId'])

    # Drop column: '__system/edits'
    dff = dff.drop(columns=['__system/edits'])

    # Drop column: '__system/formVersion'
    dff = dff.drop(columns=['__system/formVersion'])

    # Drop column: '__system/deletedAt'
    dff = dff.drop(columns=['__system/deletedAt'])

    # Rename column 'gis_location/xy/coordinates' to 'xy'
    dff = dff.rename(columns={'gis_location/xy/coordinates': 'xy'})

    # Rename column 'part_one/meter_number' to 'meter_number'
    dff = dff.rename(columns={'part_one/meter_number': 'meter_number'})

    # Rename column 'part_one/customer_name' to 'customer_name'
    dff = dff.rename(columns={'part_one/customer_name': 'customer_name'})

    # Rename column 'part_one/srn_number' to 'srn_number'
    dff = dff.rename(columns={'part_one/srn_number': 'srn_number'})

    # Rename column 'part_one/account_number' to 'account_number'
    dff = dff.rename(columns={'part_one/account_number': 'account_number'})

    # Rename column 'part_one/region' to 'region'
    dff = dff.rename(columns={'part_one/region': 'region'})

    # Rename column 'part_one/county' to 'county'
    dff = dff.rename(columns={'part_one/county': 'county'})

    # Rename column 'part_one/type_of_industry' to 'type_of_industry'
    dff = dff.rename(columns={'part_one/type_of_industry': 'type_of_industry'})

    # Rename column 'customer_name' to 'meter_installation'
    dff = dff.rename(columns={'customer_name': 'meter_installation'})

    # Rename column 'part_one_intsllation/metering_installation' to 'metering_installation'
    dff = dff.rename(columns={'part_one_intsllation/metering_installation': 'metering_installation'})

    # Rename column 'part_two/progaming_initial' to 'programming_initial'
    dff = dff.rename(columns={'part_two/progaming_initial': 'programming_initial'})

    # Rename column 'part_two/progaming_final' to 'programming_final'
    dff = dff.rename(columns={'part_two/progaming_final': 'programming_final'})

    # Rename column 'part_two/meter_terminal_initial' to 'meter_terminal_initial'
    dff = dff.rename(columns={'part_two/meter_terminal_initial': 'meter_terminal_initial'})

    # Rename column 'part_two/meter_terminal_final' to 'meter_terminal_final'
    dff = dff.rename(columns={'part_two/meter_terminal_final': 'meter_terminal_final'})

    # Rename column 'part_two/test_block_initial' to 'test_block_initial'
    dff = dff.rename(columns={'part_two/test_block_initial': 'test_block_initial'})

    # Rename column 'part_two/test_block_final' to 'test_block_final'
    dff = dff.rename(columns={'part_two/test_block_final': 'test_block_final'})

    # Rename column 'part_two/meter_body_seal_initial' to 'meter_body_seal_initial'
    dff = dff.rename(columns={'part_two/meter_body_seal_initial': 'meter_body_seal_initial'})

    # Rename column 'part_two/meter_body_seal_final' to 'meter_body_seal_final'
    dff = dff.rename(columns={'part_two/meter_body_seal_final': 'meter_body_seal_final'})

    # Rename column 'part_two/smart_meter_enclosure_initial' to 'smart_meter_enclosure_initial'
    dff = dff.rename(columns={'part_two/smart_meter_enclosure_initial': 'smart_meter_enclosure_initial'})

    # Rename column 'part_two/smart_meter_enclosure_final' to 'smart_meter_enclosure_final'
    dff = dff.rename(columns={'part_two/smart_meter_enclosure_final': 'smart_meter_enclosure_final'})

    # Rename column 'part_two/amr_initial' to 'amr_initial'
    dff = dff.rename(columns={'part_two/amr_initial': 'amr_initial'})

    # Rename column 'part_two/amr_final' to 'amr_final'
    dff = dff.rename(columns={'part_two/amr_final': 'amr_final'})

    # Rename column 'part_two/other_seals' to 'other_seals'
    dff = dff.rename(columns={'part_two/other_seals': 'other_seals'})

    # Rename column 'part_three/connection_configs' to 'connection_configs'
    dff = dff.rename(columns={'part_three/connection_configs': 'connection_configs'})

    # Rename column 'part_three/meter_voltage_atsite' to 'meter_voltage_at_site'
    dff = dff.rename(columns={'part_three/meter_voltage_atsite': 'meter_voltage_at_site'})

    # Rename column 'part_three/ct_ratio_progammed' to 'ct_ratio_programmed'
    dff = dff.rename(columns={'part_three/ct_ratio_progammed': 'ct_ratio_programmed'})

    # Rename column 'part_three/ct_ratio_prog_at_meter' to 'ct_ratio_at_meter'
    dff = dff.rename(columns={'part_three/ct_ratio_prog_at_meter': 'ct_ratio_at_meter'})

    # Rename column 'part_three/ct_ratio_installed' to 'ct_ratio_installed'
    dff = dff.rename(columns={'part_three/ct_ratio_installed': 'ct_ratio_installed'})

    # Rename column 'part_three/vt_ratio' to 'vt_ratio'
    dff = dff.rename(columns={'part_three/vt_ratio': 'vt_ratio'})

    # Rename column 'part_three/y_n' to 'ct_vt_done'
    dff = dff.rename(columns={'part_three/y_n': 'ct_vt_done'})

    # Rename column 'part_three/ct_vt_match' to 'ct_vt_match'
    dff = dff.rename(columns={'part_three/ct_vt_match': 'ct_vt_match'})

    # Rename column 'part_three/mismatch_description' to 'mismatch_description'
    dff = dff.rename(columns={'part_three/mismatch_description': 'mismatch_description'})

    # Rename column 'part_four/zera_test_done' to 'zera_test_done'
    dff = dff.rename(columns={'part_four/zera_test_done': 'zera_test_done'})

    # Rename column 'part_five/error_test_remarks' to 'error_test_remarks'
    dff = dff.rename(columns={'part_five/error_test_remarks': 'error_test_remarks'})

    # Rename column 'part_five/error_trial_per' to 'error_trial_per'
    dff = dff.rename(columns={'part_five/error_trial_per': 'error_trial_per'})

    # Rename column 'part_six/error_per' to 'error_per'
    dff = dff.rename(columns={'part_six/error_per': 'error_per'})

    # Rename column 'part_six/test_results_remarks' to 'test_results_remarks'
    dff = dff.rename(columns={'part_six/test_results_remarks': 'test_results_remarks'})

    # Rename column 'part_six/meter_pass_test' to 'meter_pass_test'
    dff = dff.rename(columns={'part_six/meter_pass_test': 'meter_pass_test'})

    # Rename column 'part_seven/red_phase_amcorder' to 'red_phase_amcorder'
    dff = dff.rename(columns={'part_seven/red_phase_amcorder': 'red_phase_amcorder'})

    # Rename column 'part_seven/red_phase_meter' to 'red_phase_meter'
    dff = dff.rename(columns={'part_seven/red_phase_meter': 'red_phase_meter'})

    # Rename column 'part_seven/yellow_phase_amcorder' to 'yellow_phase_amcoder'
    dff = dff.rename(columns={'part_seven/yellow_phase_amcorder': 'yellow_phase_amcoder'})

    # Rename column 'part_seven/yellow_phase_meter' to 'yellow_phase_meter'
    dff = dff.rename(columns={'part_seven/yellow_phase_meter': 'yellow_phase_meter'})

    # Rename column 'part_seven/blue_phase_amcorder' to 'blue_phase_amcorder'
    dff = dff.rename(columns={'part_seven/blue_phase_amcorder': 'blue_phase_amcorder'})

    # Rename column 'part_seven/blue_phase_meter' to 'blue_phase_meter'
    dff = dff.rename(columns={'part_seven/blue_phase_meter': 'blue_phase_meter'})

    # Rename column 'part_seven/load_balancing' to 'load_balancing'
    dff = dff.rename(columns={'part_seven/load_balancing': 'load_balancing'})

    # Rename column 'part_seven/m_n_clamp_currents' to 'm_n_clamp_currents'
    dff = dff.rename(columns={'part_seven/m_n_clamp_currents': 'm_n_clamp_currents'})

    # Rename column 'part_eight/time_actual' to 'time_actual'
    dff = dff.rename(columns={'part_eight/time_actual': 'time_actual'})

    # Rename column 'part_eight/date_actual' to 'date_actual'
    dff = dff.rename(columns={'part_eight/date_actual': 'date_actual'})

    # Rename column 'part_eight/date_meter' to 'date_meter'
    dff = dff.rename(columns={'part_eight/date_meter': 'date_meter'})

    # Rename column 'part_eight/current_180_kwh' to 'current_180_kwh'
    dff = dff.rename(columns={'part_eight/current_180_kwh': 'current_180_kwh'})

    # Rename column 'part_eight/memory_180_kwh' to 'memory_180_kwh'
    dff = dff.rename(columns={'part_eight/memory_180_kwh': 'memory_180_kwh'})

    # Rename column 'part_eight/image_180_kwh' to 'image_180_kwh'
    dff = dff.rename(columns={'part_eight/image_180_kwh': 'image_180_kwh'})

    # Rename column 'part_eight/current_280_kwh' to 'current_280_kwh'
    dff = dff.rename(columns={'part_eight/current_280_kwh': 'current_280_kwh'})

    # Rename column 'part_eight/memory_280_kwh' to 'memory_280_kwh'
    dff = dff.rename(columns={'part_eight/memory_280_kwh': 'memory_280_kwh'})

    # Rename column 'part_eight/image_280_kwh' to 'image_280_kwh'
    dff = dff.rename(columns={'part_eight/image_280_kwh': 'image_280_kwh'})

    # Rename column 'part_eight/current_960_kva' to 'current_960_kva'
    dff = dff.rename(columns={'part_eight/current_960_kva': 'current_960_kva'})

    # Rename column 'part_eight/memory_960_kva' to 'memory_960_kva'
    dff = dff.rename(columns={'part_eight/memory_960_kva': 'memory_960_kva'})

    # Rename column 'part_eight/current_150_kwh' to 'current_150_kwh'
    dff = dff.rename(columns={'part_eight/current_150_kwh': 'current_150_kwh'})

    # Rename column 'part_eight/memory_150_kwh' to 'memory_150_kwh'
    dff = dff.rename(columns={'part_eight/memory_150_kwh': 'memory_150_kwh'})

    # Rename column 'part_eight/current_181_kwh' to 'current_181_kwh'
    dff = dff.rename(columns={'part_eight/current_181_kwh': 'current_181_kwh'})

    # Rename column 'part_eight/current_182_kwh' to 'current_182_kwh'
    dff = dff.rename(columns={'part_eight/current_182_kwh': 'current_182_kwh'})

    # Rename column 'part_eight/memory_182_kwh' to 'memory_182_kwh'
    dff = dff.rename(columns={'part_eight/memory_182_kwh': 'memory_182_kwh'})

    # Rename column 'part_eight/instatenious_970_kva' to 'instateneous_970_kva'
    dff = dff.rename(columns={'part_eight/instatenious_970_kva': 'instateneous_970_kva'})

    # Rename column 'part_eight/instatenious_170_kva' to 'instateneous_170_kva'
    dff = dff.rename(columns={'part_eight/instatenious_170_kva': 'instateneous_170_kva'})

    # Rename column 'part_eight/red_phase_voltage' to 'red_phase_voltage'
    dff = dff.rename(columns={'part_eight/red_phase_voltage': 'red_phase_voltage'})

    # Rename column 'part_eight/yellow_phase_voltage' to 'yellow_phase_voltage'
    dff = dff.rename(columns={'part_eight/yellow_phase_voltage': 'yellow_phase_voltage'})

    # Rename column 'part_eight/blue_phase_voltage' to 'blue_phase_voltage'
    dff = dff.rename(columns={'part_eight/blue_phase_voltage': 'blue_phase_voltage'})

    # Rename column 'part_eight/red_phase_current' to 'red_phase_current'
    dff = dff.rename(columns={'part_eight/red_phase_current': 'red_phase_current'})

    # Rename column 'part_eight/yellow_phase_current' to 'yellow_phase_current'
    dff = dff.rename(columns={'part_eight/yellow_phase_current': 'yellow_phase_current'})

    # Rename column 'part_eight/blue_phase_current' to 'blue_phase_current'
    dff = dff.rename(columns={'part_eight/blue_phase_current': 'blue_phase_current'})

    # Rename column 'part_eight/power_factor' to 'power_factor'
    dff = dff.rename(columns={'part_eight/power_factor': 'power_factor'})

    # Rename column 'part_eight/reading_remarks' to 'reading_remarks'
    dff = dff.rename(columns={'part_eight/reading_remarks': 'reading_remarks'})

    # Rename column 'part_nine/solar_installation' to 'solar_installation'
    dff = dff.rename(columns={'part_nine/solar_installation': 'solar_installation'})

    # Rename column 'part_nine/solar_size' to 'solar_size'
    dff = dff.rename(columns={'part_nine/solar_size': 'solar_size'})

    # Rename column 'part_nine/solar_installation_date' to 'solar_installation_date'
    dff = dff.rename(columns={'part_nine/solar_installation_date': 'solar_installation_date'})

    # Rename column 'part_ten/overall_remarks' to 'overall_remarks'
    dff = dff.rename(columns={'part_ten/overall_remarks': 'overall_remarks'})

    # Rename column 'part_ten/declaration' to 'declaration'
    dff = dff.rename(columns={'part_ten/declaration': 'declaration'})

    # Rename column 'meta/instanceID' to 'instance_id'
    dff = dff.rename(columns={'meta/instanceID': 'instance_id'})

    # Rename column '__system/submissionDate' to 'submission_date'
    dff = dff.rename(columns={'__system/submissionDate': 'submission_date'})

    # Rename column 'meta/instanceName' to 'instance_name'
    dff = dff.rename(columns={'meta/instanceName': 'instance_name'})

    # Drop column: '__system/updatedAt'
    dff = dff.drop(columns=['__system/updatedAt'])

    # Rename column '__system/submitterId' to 'submitter_id'
    dff = dff.rename(columns={'__system/submitterId': 'submitter_id'})

    # Rename column '__system/submitterName' to 'submitter_name'
    dff = dff.rename(columns={'__system/submitterName': 'submitter_name'})

    dff.to_csv('lp_cleaned.csv')

In [6]:
clean(dff)

In [ ]:
analysed = analysed.groupby(['meter_type']).agg(id_count=('id', 'count')).reset_index()

In [24]:
analysed = pd.read_csv('transf_data.csv')
analysed

,Unnamed: 0,start,end,phone_number,id,coordinates,meter_type,meter_scale,ordinary_metrtype,cable_installation,...,part_ten/l_terminalcover,part_ten/r_terminalcover,part_ten/meter_box,part_ten/seal_color,remarks,units,validation,meta/instanceID,submission_date,inspector
0,0,2025-01-16T16:06:04.080+03:00,2025-01-16T16:07:27.024+03:00,NaN,uuid:6d6b078f-1291-4c3d-948d-e3c87f7f3f4c,"[36.968894, -1.1513819, 1500.4000244140625]",ORDINARY,SINGLE_SCALE,NON_SMART,Three-phase Overhead,...,B,B,H,YELLOW,NaN,0,0,uuid:6d6b078f-1291-4c3d-948d-e3c87f7f3f4c,2025-01-16T13:07:28.626Z,kpl16314
1,1,2024-12-27T17:10:14.673+03:00,2024-12-27T17:10:28.749+03:00,NaN,uuid:7adce152-745a-4572-8a90-e1097e52c082,"[36.9660287, -1.1501501, 0]",LP,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,uuid:7adce152-745a-4572-8a90-e1097e52c082,2024-12-27T14:10:29.969Z,kpl16314
2,2,2024-12-26T09:47:39.315+03:00,2024-12-26T09:49:16.450+03:00,NaN,uuid:d5c961cc-c766-483b-a792-0ea269153432,"[36.9687976, -1.1515371, 1501.9000244140625]",ORDINARY,FOUR_SCALE,NON_SMART,Single-phase Underground,...,Yg,Ggt,Gcv,YELLOW,NaN,0,0,uuid:d5c961cc-c766-483b-a792-0ea269153432,2024-12-26T06:49:17.729Z,kpl16314

In [26]:
analysed = analysed.groupby(['submission_date']).agg(id_count=('id', 'count')).reset_index()
analysed

  submission_date  id_count
0      2024-12-26         1
1      2024-12-27         1
2      2025-01-16         1

In [25]:
analysed['submission_date'] = pd.to_datetime(analysed['submission_date'])
analysed['submission_date'] = analysed['submission_date'].dt.date
analysed['submission_date']

0    2025-01-16
1    2024-12-27
2    2024-12-26
Name: submission_date, dtype: object

In [ ]:
from pyodk.client import Client

# Configuration for your ODK Central server
config = {
    "base_url": "https://rri.kplcinstitute.ac.ke/",
    "username": "inthusa@kplc.co.ke",
    "password": "Jayden29.Facilities",
    "project_id": 8,         # The ID of your project
    "form_id": "lp_2025_2026"  # The XML Form ID
}



try:
    # Initialize the client
    client = Client(config=config)

    # Fetch submission data from the specified form
    submissions = client.submissions.get_table()

    # The 'value' key holds a list of all submission dictionaries
    for sub in submissions["value"]:
        print(f"--- Submission Instance ID: {sub['__id']} ---")

        # The actual form data is in the main dictionary
        # 'meta' and '__id' are system properties added by ODK Central
        
        # Example of accessing data (assuming 'name' and 'age' are your question IDs)
        # name = sub.get("name", "N/A")
        # age = sub.get("age", "N/A")

        # print(f"Name: {name}")
        # print(f"Age: {age}")
        
        # You can also just print the whole data dictionary to see its structure
        print("Full data:", sub)
        print("-" * 40)

except Exception as e:
    print(f"An error occurred: {e}")
















       meter_number TEXT
        customer_name TEXT
        srn_number TEXT
        account_number TEXT
        region TEXT
        county TEXT
        type_of_industry TEXT
        metering_installation TEXT
        progaming_initial TEXT
        progaming_final TEXT
        meter_terminal_initial TEXT
        meter_terminal_final TEXT
        test_block_initial TEXT
        test_block_final TEXT
        meter_body_seal_initial TEXT
        meter_body_seal_final TEXT
        smart_meter_enclosure_initial TEXT
        smart_meter_enclosure_final TEXT
        amr_initial TEXT
        amr_final TEXT
        other_seals TEXT
        connection_configs TEXT
        meter_voltage_atsite TEXT
        ct_ratio_progammed TEXT
        ct_ratio_prog_at_meter TEXT
        ct_ratio_installed TEXT
        vt_ratio TEXT
        y_n TEXT
        ct_vt_match TEXT
        mismatch_description TEXT
        zera_test_done TEXT
        error_trial_per TEXT
        error_test_remarks TEXT
        error_per tEXT
        test_results_remarks TEXT
        meter_pass_test TEXT
        red_phase_amcorder TEXT
        red_phase_meter tEXT
        yellow_phase_amcorder TEXT
        yellow_phase_meter TEXT
        blue_phase_amcorder TEXT
        blue_phase_meter TEXT
        load_balancing TEXT
        m_n_clamp_currents tEXT
        time_actual TEXT
        time_meter TEXT
        date_actual TEXT
        date_meter TEXT
        current_180_kwh TEXT
        memory_180_kwh TEXT
        image_180_kwh TEXT
        current_280_kwh TEXT
        memory_280_kwh TEXT
        image_280_kwh TEXT
        current_960_kva TEXT
        memory_960_kva TEXT
        current_150_kwh TEXT
        memory_150_kwh TEXT
        current_181_kwh TEXT
        memory_181_kwh TEXT
        current_182_kwh TEXT
        memory_182_kwh TEXT
        instatenious_970_kva TEXT
        instatenious_170_kva TEXT
        red_phase_voltage TEXT
        yellow_phase_voltage TEXT
        blue_phase_voltage TEXT
        red_phase_current TEXT
        yellow_phase_current TEXT
        blue_phase_current TEXT
        power_factor TEXT
        reading_remarks TEXT
        solar_installation TEXT
        solar_size TEXT
        solar_installation_date TEXT
        overall_remarks TEXT
        declaration TEXT

An error occurred: Client.__init__() got an unexpected keyword argument 'config'

: